version: '3'
services:
  # nginx-gateway:
  #   build:
  #     context: .
  #   restart: always
  #   networks:
  #     - kanban-net
  #   ports:
  #     - "80:80"

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: xy2089
      TZ: Asia/Shanghai
    networks:
      - kanban-net
    ports:
      - 3306:3306
    volumes:
      - kanban-db:/var/lib/mysql
      - ./scripts/mysql/cmysql.cnf:/etc/mysql/conf.d/custom.cnf
      - ./scripts/mysql/:/docker-entrypoint-initdb.d/
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      timeout: 30s
      retries: 10

    command: --max_connections=1000 --character-set-server=utf8mb4 --collation-server=utf8mb4_general_ci
  redis:
    image: redis:alpine3.17
    restart: always
    ports:
      - 6379:6379
    environment:
      TZ: Asia/Shanghai
    volumes:
      - kanban-redis:/data
    networks:
      - kanban-net
    healthcheck:
      test: [ "CMD-SHELL", "redis-cli ping | grep PONG" ]
      interval: 1s
      timeout: 3s
      retries: 5
  server:
    build: ./server
    networks:
      - kanban-net
    depends_on:
      - db:
          condition: service_healthy
      - redis:
          condition: service_healthy
  web:
    build:
      context: ./web
    ports:
      - 80:80
    networks:
      - kanban-net
    depends_on:
      - server

volumes:
  kanban-db:
  kanban-redis:
networks:
  kanban-net:
